imports:
  - { resource: Backend/DashboardWidgets.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  F7media\Cacheflow\:
    resource: '../Classes/*'

  F7media\Cacheflow\Command\FlowCacheCommand:
    tags:
      - name: 'console.command'
        command: 'cacheflow:process'
        description: 'Regenerates cached pages'
